### ISSUE TITLE
sending-to-an-rtmp-server needs location example 

### ISSUE THREAD

**Issue by CarlFK** [matthew1000/gstreamer-cheat-sheet#5]
```
gst-launch-1.0 videotestsrc  is-live=true ! \
    queue ! x264enc ! flvmux name=muxer ! rtmpsink location="$RTMP_DEST live=1"
```
https://github.com/matthew1000/gstreamer-cheat-sheet/blob/master/rtmp.md#sending-to-an-rtmp-server

RTMP_DEST isn't defined.

it would be great if I knew how to make it work with an example from 
https://github.com/arut/nginx-rtmp-module

I'm currently trying different things, all give me:
Could not connect to RTMP stream "rtmp://localhost/xyz/ live=1" for writing

for all xyz

**Comment by matthew1000** [comment]
Hi, thanks for this. I've updated the page to state that `RTMP_DEST` needs setting I've also provided a basic example for configuring nginx.
